### ISSUE TITLE
Deploy somewhere??

### ISSUE THREAD

**Issue by dustinmichels** [CRAP-at-Carleton/CRAP#5]
@simonbilskyrollins , do you have any preference for react deployment? More Heroku?

**Comment by dustinmichels** [comment]
[crap-at-carleton.io?](https://shop.gandi.net/en/domain/suggest/ae51b494-7e80-4bc2-ba97-1970732333e5?search=crap-at-carleton)

[crap-carleton.io?](https://shop.gandi.net/en/domain/suggest/ae51b494-7e80-4bc2-ba97-1970732333e5?search=crap-carleton)

**Comment by simonbilskyrollins** [comment]
Yeah Heroku would be my first choice just because I've used it before and it's been easy to setup. I'll do that later today.

**Comment by simonbilskyrollins** [comment]
Done! crap-carleton.herokuapp.com
